# Site settings
title_left    : "ross"
title_right   : "turk" # default: ""
description   : "Ecosystems, technologies, markets."
keywords      : "ecosystems, technology, markets, open source, engineering, communities"
url           : http://text.rtrk.us # site url
baseurl       : "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover         : "" # image uri like logo/cover image for site seo

google_analytics  : UA-XXXXX-XX
twitter_username  : "rossturk"
comments_enabled  : false # if enabled (set to true), please provide your disqus_username
disqus_shortname  : ""
postshare_enabled : false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source      : ./
destination : ./_site

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Author settings
author:
  name     : "Ross Turk"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - name: Work
    link: /work.html
  - name: Videos
    link: /videos.html

collections:
  work:
    output: true
    
defaults:
  - scope:
      path: ""
      type: "work"
    values:
      layout: "work"
  
exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md", "script"]
